spring:
  config:
    import: "file:./stage.yml"

  application:
    name: Exercise

  datasource:
    url: "${spring.datasource.url}"
    username: "${spring.datasource.username}"
    password: "${spring.datasource.password}"

springdoc:
  swagger-ui:
    enabled: true
    operationsSorter: alpha

jwt:
  secret:
    key: "${jwt.secret.key}"

logging:
  level:
    jwt: DEBUG
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
      springframework:
        web: debug
        security: TRACE
        transaction: debug

swagger:
  server:
    local:
      url: http://localhost:8080
    prod:
      url: https://eray.ordanuc.com
