spring:
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:file:./stage.yml}

  application:
    name: Exercise

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zone: Europe/Istanbul

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Istanbul

server:
  time-zone: Europe/Istanbul

springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.username}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    jwt: DEBUG
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        web: DEBUG
        security: TRACE
        transaction: DEBUG

jwt:
  secret:
    key: ${jwt.secret.key}

firebase:
  credentials:
    path: ${firebase.credentials.path}

auth:
  admin:
    usernames: ${auth.admin.usernames}
    emails: ${auth.admin.emails}

aws:
  accessKeyId: ${aws.accessKeyId}
  secretKey: ${aws.secretKey}
  region: ${aws.region}
  s3:
    bucket: ${aws.s3.bucket}

swagger:
  server:
    local:
      url: http://localhost:8080
    prod:
