spring:
  config:
    import: "file:./stage.yml"

  application:
    name: Exercise

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  jackson:
    time-zone: Europe/Istanbul

  doc:
    swagger-ui:
      enabled: true
      operations-sorter: alpha

logging:
  level:
    jwt: DEBUG
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        web: DEBUG
        security: TRACE
        transaction: DEBUG

jwt:
  secret:
    key: ${jwt.secret.key}

swagger:
  server:
    local:
      url: http://localhost:8080
    prod:
