DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS notes;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE,
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255)
);

-- CREATE TABLE IF NOT EXISTS notes (
--   id SERIAL PRIMARY KEY,
--   title TEXT,
--   content TEXT,
--   author_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
--   is_favorited BOOLEAN DEFAULT FALSE,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   deleted_at TIMESTAMP DEFAULT NULL
-- );
